container:
  image: golang:latest

env:
  GOPROXY: https://goproxy.io

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./main.go
  test_script: go test ./adt